language: cpp
compiler:
- clang
os:
- linux
- osx
dist: xenial
osx_image: xcode10.3
env:
  matrix:
  - CONFIG=RELEASE QT=515 BREW=@5.15 PPA=beineri/opt-qt-5.15.0-xenial BUILD_DIR="$TRAVIS_BUILD_DIR-build"
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    sudo add-apt-repository -y ppa:$PPA;
    sudo apt-get -qy update;
  fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update;
  fi
install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    sudo apt-get -qy install doxygen graphviz lcov extra-cmake-modules libgl1-mesa-dev;
    sudo apt-get -qy install qt${QT}base qt${QT}xmlpatterns qt${QT}tools;
    gem install lcoveralls;

    mkdir exiv2 && cd exiv2;
    git clone https://github.com/Exiv2/exiv2.git . ;
    git checkout tags/v0.27.2 -b v0.27.2;
    mkdir build && cd build;
    cmake .. -DCMAKE_BUILD_TYPE=Release;
    cmake --build .;
    sudo make install && sudo ldconfig;
    cd ../../;
  fi
# brew install exiv2 (0.27.3) causes some crashes we use 0.27.2
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew install doxygen graphviz qt5 openssh;
    brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/6a39dfa5a1b2c379f41b2a2f55c8baae75e0d553/Formula/exiv2.rb;
    brew link --force qt5;
  fi
before_script:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    if [[ "$PPA" == *"/opt-"* ]]; then
      source /opt/qt$QT/bin/qt$QT-env.sh;
      export QMAKESPEC=linux-clang;
    fi;
  fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    export PATH=$PATH:$(brew --prefix qt5)/bin;
    sudo ln -s $(brew --prefix qt5)/mkspecs /usr/local/mkspecs;
    sudo ln -s $(brew --prefix qt5)/plugins /usr/local/plugins;
  fi
script:
- cd $TRAVIS_BUILD_DIR
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    chmod +x build-linux.sh;
    ./build-linux.sh;
  fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    chmod +x build-osx.sh;
    ./build-osx.sh;
  fi
before_deploy:
- ls -al releases/
deploy:
  provider: releases
  api_key:
    secure: q9quF4drNFQ+BSCT/nqozfVlvwr5oqUOIkM11WyJBfE6iAN5Oz9IVxvWIkN7thlF94OT3aReOiF5Y3DBKNOA1mYCKAu7Bx7v8cRogfgn/ICQiFmxvRDZ/b7w0AlIq3Iw+9KKAKAwJrDwBC7GSCD4YuY4crvZFIuCQIfBjUaxShiZs8DgKaRIYa3YdOLKe5SrXgYJ/ENpsaLmAQMBTWrsffr2fALLD3A8OkuLtiGmj55e4bO5r1uwrtXKU1QVlhKTv+nZATQMJ0/pBzLbHpF+toM2S5ZTwrfkRfEZMxHc+FF+HqFUpOPTRtXte+XVjBPa1tXVXoS4m4z/ZYI5eOejvVikOs6TzLar/xvXstIWV0ewtwuzEMOgzYp7ENV+db4LZz1AWfxRnFqM/d1vx810t+upVb9g7nCSWB81aYzq48W2I0Bwrf52/3Y8t7NpinhVwtj1KovlVMpthY/lxgF97c9K6PdzrFBdHb1Lm5zRrrVacdSfvezUYGxkaXIsJzM/4lU3JvcdjlGHE9EVuQwCalPLPJpuyWXBKHzEh7CYfMluyKWpp2WkPaKP5i2a3S9IiNNyODXZOBz0S+6PDUSloSYJXfPH8zbm4zV5wTjwxDNbn6oqRY98H2fu2rpd9v1QQehF7le51VQUwsiHtsN273gPs9B3LTt86AfUuMFCwFw=
  file: "releases/*"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: scheckmedia/ImageMosaicWall
